config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
#controller pages

  root 'pages#home'

  get 'about' => 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	belongs_to :user, :optional => true

	has_attached_file :cover, styles: { medium: "300x>", thumb: "100x>" }
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
  	message: "Only image files are supported"

  	has_attached_file :allegato 
  	validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ], 
  	message: "This format is not supported"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @contents = Content.all
  end


  def show
  end

  
  def new
    @content = current_user.contents.build
  end

  def edit
  end


  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover, :allegato)
    end

    def check_user
      if current_user != @content.user
        redirect_to root_url, alert: "Sorry, you do not have permission to see this page"
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, html: { multipart: true } do |form| %>
  
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titolo %>
    <%= form.text_field :titolo %>
  </div>

  <div class="field">
    <%= form.label :descrizione %>
    <%= form.text_area :descrizione %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

   <div class="field">
    <%= form.label :allegato %>
    <%= form.file_field :allegato %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>

<table>
  <thead>
    <tr>
      <th>Preview</th>
      <th>Titolo</th>
      <th>Description</th>
      <th>User</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= image_tag content.cover.url(:thumb) %></td>
        <td><%= content.titolo %></td>
        <td><%= content.descrizione %></td>
        <td><%= content.user.name %></td>
        <td><%= content.price %></td>
        <td><%= link_to 'Show', content %></td>
        <% if content.user == current_user %>
          <td><%= link_to 'Edit', edit_content_path(content) %></td>
          <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @content.cover.url(:medium) %>

<p>
  <strong>Titolo:</strong>
  <%= @content.titolo %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @content.descrizione %>
</p>

<p>
  <strong>Price:</strong>
  <%= @content.price %>
</p>

<% if @content.user == current_user %>
	<%= link_to 'Edit', edit_content_path(@content) %> |
<% end %>

<%= link_to 'Back', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer #cddc39 lime">

  <div class="footer-copyright">
    <div class="container">

       <div class="row">
          <div class="col s4">
            © 2020 FranGia95
          </div>
          <div class="col s4">
            Social
          </div>
          <div class="col s4">
            <%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
          </div>
        </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
  <nav class="#cddc39 lime">
    <div class="container nav-wrapper">
      <%= link_to "LacerMrkt", root_path, class: "brand-logo" %>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "About", about_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>

      </ul>

      <ul class="sidenav" id="mobile-demo">
        <li><%= link_to "About", about_path %></li>
      
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>LacerMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

 <%= render "layouts/header" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <main class=container >
     <%= yield %>
  </main>
  
<%= render "layouts/footer" %>

</body>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

      <script>
        $(document).ready(function(){
          $('.sidenav').sidenav();
        });
      </script>

</html>

app/views/pages/about.html.erb
<h1>About LacerMrkt</h1>
<p>LacerMrkt is a place for our customers to buy, sell and exchange their preloved clothing, shoes and accessories. Our concept was developed around sustainability, affordability and waste reduction, with the intention to engage with customers and encourage them to make ethical and sustainable fashion choices.

With multiple digital locations now on facebbok, Instagram and Pinterest, as well as our market.lacerba.fg website, SWOP’s ever-growing network aims to disrupt the wasteful practices of the current fashion industry at large by offering an alternative...</p>

app/views/pages/home.html.erb
<%# Header %>
<h1>LacerMrkt</h1>
<h2>Buy, sell & exchange secondhand goodies</h2>

	<%= link_to "SHOP NOW", root_path %>

<%# Plus: why you should choose us %>
<p>
	<%= link_to "Plus1", root_path %>
	<%= link_to "Plus2", root_path %>
	<%= link_to "Plus3", root_path %>
</p>
<%# Footer %>